[package]
org = "dilhasha"
name = "pocproject4"
version = "0.1.0"

[[platform.java11.dependency]]
path = "../../../Downloads/mysql-connector-java-8.0.26/mysql-connector-java-8.0.26.jar"
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"